### ISSUE TITLE
启动直接崩溃问题

### ISSUE THREAD

**Issue by LiJinJinJIn** [limpoxe/Android-Plugin-Framework#100]
2022-10-13 15:27:42.916 9179-9179/com.losangelescuckcurry.bullsdisgusted E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.losangelescuckcurry.bullsdisgusted:plugin, PID: 9179
    java.lang.RuntimeException: Unable to get provider com.limpoxe.fairy.manager.PluginManagerProvider: java.lang.IllegalStateException: not inited yet
        at android.app.ActivityThread.installProvider(ActivityThread.java:6678)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6220)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6135)
        at android.app.ActivityThread.access$1200(ActivityThread.java:235)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.IllegalStateException: not inited yet
        at com.limpoxe.fairy.core.FairyGlobal.getHostApplication(FairyGlobal.java:28)
        at com.limpoxe.fairy.manager.PluginManagerService.getSharedPreference(PluginManagerService.java:426)
        at com.limpoxe.fairy.manager.PluginManagerService.readPlugins(PluginManagerService.java:467)
        at com.limpoxe.fairy.manager.PluginManagerService.loadEnabledPlugins(PluginManagerService.java:67)
        at com.limpoxe.fairy.manager.PluginManagerProvider.onCreate(PluginManagerProvider.java:122)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6673)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6220) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6135) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:235) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6981) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by limpoxe** [comment]
Caused by: java.lang.IllegalStateException: not inited yet
at com.limpoxe.fairy.core.FairyGlobal.getHostApplication(FairyGlobal.java:28)

初始化错误，检查下这个PluginLoader.initLoader()函数调了没有
