### ISSUE TITLE
设置theme时,android_content_AssetManager_applyThemeStyle 没有返回

### ISSUE THREAD

**Issue by simonwu-os** [limpoxe/Android-Plugin-Framework#11]
在加载我自己定义的apk，在启动activity时，
发现在调用 resetActivityContext 函数时，
这一段代码
         // 重设theme
        if (pluginAppTheme != 0) {
            RefInvoker.setFieldObject(activity, ContextThemeWrapper.class.getName(),   android_content_ContextThemeWrapper_mTheme, null);
                       activity.setTheme(pluginAppTheme);
                 }
在运行时，有点像死锁，不过线程的状态还是RUNNABLE,但 activity.setTheme(pluginAppTheme);这语句就是不返回。 手机是华为的荣耀4. 应该是调用native的方法android_content_AssetManager_applyThemeStyle没有返回，一直在运行。

"<1> main@830026030872" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
      at android.content.res.AssetManager.applyThemeStyle(AssetManager.java:-1)
      at android.content.res.Resources$Theme.applyStyle(Resources.java:1256)
      at android.view.ContextThemeWrapper.onApplyThemeResource(ContextThemeWrapper.java:132)
      at android.app.Activity.onApplyThemeResource(Activity.java:3413)
      at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:144)
      at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:89)
      at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:89)
      at com.plugin.core.PluginInjector.resetActivityContext(PluginInjector.java:221)
      at com.plugin.core.PluginInjector.injectActivityContext(PluginInjector.java:185)
      at com.plugin.core.PluginInstrumentionWrapper.callActivityOnCreate(PluginInstrumentionWrapper.java:145)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
      at android.app.ActivityThread.access$1100(ActivityThread.java:141)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
      at com.plugin.core.PluginAppTrace.handleMessage(PluginAppTrace.java:41)
      at android.os.Handler.dispatchMessage(Handler.java:98)
      at android.os.Looper.loop(Looper.java:136)
      at android.app.ActivityThread.main(ActivityThread.java:5336)
      at java.lang.reflect.Method.invokeNative(Method.java:-1)
      at java.lang.reflect.Method.invoke(Method.java:515)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
      at dalvik.system.NativeStart.main(NativeStart.java:-1)

"<7> FinalizerDaemon@830030521168" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
      at java.lang.Object.wait(Object.java:-1)
      at java.lang.Object.wait(Object.java:401)
      at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:102)
      at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:73)
      at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
      at java.lang.Thread.run(Thread.java:841)

"<8> FinalizerWatchdogDaemon@830030521600" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
      at java.lang.Object.wait(Object.java:-1)
      at java.lang.Object.wait(Object.java:364)
      at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:230)
      at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:207)
      at java.lang.Thread.run(Thread.java:841)

"<6> ReferenceQueueDaemon@830030520808" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
      at java.lang.Object.wait(Object.java:-1)
      at java.lang.Object.wait(Object.java:364)
      at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:130)
      at java.lang.Thread.run(Thread.java:841)

"<10> Binder_2@830030544912" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
      at dalvik.system.NativeStart.run(NativeStart.java:-1)

"<9> Binder_1@830030544672" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
      at dalvik.system.NativeStart.run(NativeStart.java:-1)

"<5> Compiler@830030520568" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
      at dalvik.system.NativeStart.run(NativeStart.java:-1)

"<3> Signal Catcher@830030520088" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
      at dalvik.system.NativeStart.run(NativeStart.java:-1)

"<2> GC@830030519864" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
      at dalvik.system.NativeStart.run(NativeStart.java:-1)

**Comment by simonwu-os** [comment]
I've resolved it.  
In the method: PluginInjector.resetActivityContext
change the statement:
RefInvoker.setFieldObject(activity, ContextThemeWrapper.class.getName(), android_content_ContextThemeWrapper_mResources, null);
into the two statements:

RefInvoker.setFieldObject(activity, ContextThemeWrapper.class.getName(), android_content_ContextThemeWrapper_mResources, pluginContext.getResources());
        RefInvoker.setFieldObject(activity, activity.getClass(), android_content_ContextThemeWrapper_mResources, pluginContext.getResources());

**Comment by limpoxe** [comment]
谢谢。这个问题是由于在插件的activity或其基类中定义了mResource对象，并重写了activity的getResource导致的。例如supportV7的AppcompatActivity。
你的改法确实可以解决问题。

**Comment by limpoxe** [comment]
已修复
