### ISSUE TITLE
某些机型插件中发送自定义布局的Notification会出现异常

### ISSUE THREAD

**Issue by Walkud** [limpoxe/Android-Plugin-Framework#18]
### 出问题机型

华为Mate8 NXT-AL10 系统： 6.0
华为SCL-AL00  系统：5.1.1
华为MT7-TL10 系统： 6.0
### 问题描述

发送自定义布局通知出现异常，可能会出现跳转黑屏、邮件、短信、手机主屏的情况

```

###异常日志

android.app.RemoteServiceException: Bad notification posted from package com.born.mobile.wom.inside: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.born.mobile.wom.inside user=UserHandle{0} id=1 tag=null score=0 key=0|com.born.mobile.wom.inside|1|null|10192: Notification(pri=0 contentView=com.born.mobile.wom.inside/0x7f040057 vibrate=null sound=null tick defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE))
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
    at com.plugin.core.PluginAppTrace.handleMessage(PluginAppTrace.java:41)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:150)
    at android.app.ActivityThread.main(ActivityThread.java:5546)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)

```

**Comment by jason0539** [comment]
请问这个问题如何解决的
