### ISSUE TITLE
请问一下，这个插件框架是不是不支持bindservice

### ISSUE THREAD

**Issue by jisuz** [limpoxe/Android-Plugin-Framework#33]
今晚做了一个demo测试了一下，发现再使用bindService的时候出现了错误

**Comment by jisuz** [comment]
记录错误日志
                                                                               java.lang.RuntimeException: Unable to create service %org.fourthline.cling.android.AndroidUpnpServiceImpl: java.lang.reflect.UndeclaredThrowableException
                                                                                   at com.limpoxe.fairy.core.PluginShadowService.callServiceOnCreate(PluginShadowService.java:74)
                                                                                   at com.limpoxe.fairy.core.PluginShadowService.onCreate(PluginShadowService.java:34)
                                                                                   at android.app.ActivityThread.handleCreateService(ActivityThread.java:2702)
                                                                                   at android.app.ActivityThread.access$2100(ActivityThread.java:139)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
                                                                                   at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5314)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                                Caused by: java.lang.reflect.UndeclaredThrowableException
                                                                                   at $Proxy9.acquireMulticastLock(Native Method)
                                                                                   at android.net.wifi.WifiManager$MulticastLock.acquire(WifiManager.java:2077)
                                                                                   at org.fourthline.cling.android.AndroidRouter.setWiFiMulticastLock(AndroidRouter.java:171)
                                                                                   at org.fourthline.cling.android.AndroidRouter.enable(AndroidRouter.java:95)
                                                                                   at org.fourthline.cling.UpnpServiceImpl.<init>(UpnpServiceImpl.java:87)
                                                                                   at org.fourthline.cling.android.AndroidUpnpServiceImpl$1.<init>(AndroidUpnpServiceImpl.java:54)
                                                                                   at org.fourthline.cling.android.AndroidUpnpServiceImpl.onCreate(AndroidUpnpServiceImpl.java:54)
                                                                                   at com.limpoxe.fairy.core.PluginShadowService.callServiceOnCreate(PluginShadowService.java:70)
                                                                                   at com.limpoxe.fairy.core.PluginShadowService.onCreate(PluginShadowService.java:34) 
                                                                                   at android.app.ActivityThread.handleCreateService(ActivityThread.java:2702) 
                                                                                   at android.app.ActivityThread.access$2100(ActivityThread.java:139) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348) 
                                                                                   at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5314) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                                Caused by: java.lang.reflect.InvocationTargetException
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.limpoxe.fairy.core.proxy.MethodHandler.invoke(MethodHandler.java:37)
                                                                                   at $Proxy9.acquireMulticastLock(Native Method) 
                                                                                   at android.net.wifi.WifiManager$MulticastLock.acquire(WifiManager.java:2077) 
                                                                                   at org.fourthline.cling.android.AndroidRouter.setWiFiMulticastLock(AndroidRouter.java:171) 
                                                                                   at org.fourthline.cling.android.AndroidRouter.enable(AndroidRouter.java:95) 
                                                                                   at org.fourthline.cling.UpnpServiceImpl.<init>(UpnpServiceImpl.java:87) 
                                                                                   at org.fourthline.cling.android.AndroidUpnpServiceImpl$1.<init>(AndroidUpnpServiceImpl.java:54) 
                                                                                   at org.fourthline.cling.android.AndroidUpnpServiceImpl.onCreate(AndroidUpnpServiceImpl.java:54) 
                                                                                   at com.limpoxe.fairy.core.PluginShadowService.callServiceOnCreate(PluginShadowService.java:70) 
                                                                                   at com.limpoxe.fairy.core.PluginShadowService.onCreate(PluginShadowService.java:34) 
                                                                                   at android.app.ActivityThread.handleCreateService(ActivityThread.java:2702) 
                                                                                   at android.app.ActivityThread.access$2100(ActivityThread.java:139) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348) 
                                                                                   at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5314) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                                Caused by: java.lang.SecurityException: WifiService: Neither user 10049 nor current process has android.permission.CHANGE_WIFI_MULTICAST_STATE.
                                                                                   at android.os.Parcel.readException(Parcel.java:1468)
                                                                                   at android.os.Parcel.readException(Parcel.java:1422)
                                                                                   at android.net.wifi.IWifiManager$Stub$Proxy.acquireMulticastLock(IWifiManager.java:1133)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.limpoxe.fairy.core.proxy.MethodHandler.invoke(MethodHandler.java:37) 
                                                                                   at $Proxy9.acquireMulticastLock(Native Method) 
                                                                                   at android.net.wifi.WifiManager$MulticastLock.acquire(WifiManager.java:2077) 
                                                                                   at org.fourthline.cling.android.AndroidRouter.setWiFiMulticastLock(AndroidRouter.java:171) 
                                                                                   at org.fourthline.cling.android.AndroidRouter.enable(AndroidRouter.java:95) 
                                                                                   at org.fourthline.cling.UpnpServiceImpl.<init>(UpnpServiceImpl.java:87) 
                                                                                   at org.fourthline.cling.android.AndroidUpnpServiceImpl$1.<init>(AndroidUpnpServiceImpl.java:54) 
                                                                                   at org.fourthline.cling.android.AndroidUpnpServiceImpl.onCreate(AndroidUpnpServiceImpl.java:54) 
                                                                                   at com.limpoxe.fairy.core.PluginShadowService.callServiceOnCreate(PluginShadowService.java:70) 
                                                                                   at com.limpoxe.fairy.core.PluginShadowService.onCreate(PluginShadowService.java:34) 
                                                                                   at android.app.ActivityThread.handleCreateService(ActivityThread.java:2702) 
                                                                                   at android.app.ActivityThread.access$2100(ActivityThread.java:139) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348) 
                                                                                   at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5314) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by limpoxe** [comment]
@jisuz 

仔细看log。。

Caused by: java.lang.SecurityException: WifiService: Neither user 10049 nor current process has android.permission.CHANGE_WIFI_MULTICAST_STATE.

**Comment by jisuz** [comment]
谢谢，谢谢！是我最近的疏忽，忘记把权限配置加入到demo中。。。。。
