### ISSUE TITLE
demo在nexus6p，7.1.1上的crash

### ISSUE THREAD

**Issue by liwshuo** [limpoxe/Android-Plugin-Framework#36]
nexus6p，7.1.1上的crash
安装完成后打开，点击”打开插件，PluginHelloWorld“，会crash，日志如下。
如果点了最后一个”测试宿主tabActivity内嵌插件Activity“，然后再点击”打开插件，PluginHelloWorld“，就可以正常运行了。
`android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class org.chromium.chrome.browser.widget.accessibility.AccessibilityTabModelListItem
                                                                               Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class org.chromium.chrome.browser.widget.accessibility.AccessibilityTabModelListItem
                                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.widget.accessibility.AccessibilityTabModelListItem" on path: DexPathList[[zip file "/data/user/0/com.example.pluginmain/app_plugin_dir/com.example.pluginhelloworld/1.0.1_2/base-1.apk"],nativeLibraryDirectories=[/data/user/0/com.example.pluginmain/app_plugin_dir/com.example.pluginhelloworld/1.0.1_2/lib, /system/lib, /vendor/lib]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                   at com.limpoxe.fairy.core.PluginClassLoader.findClass(PluginClassLoader.java:101)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:609)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
                                                                                   at com.example.pluginhelloworld.WelcomeActivity.onCreate(WelcomeActivity.java:52)
                                                                                   at android.app.Activity.performCreate(Activity.java:6679)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                   at com.limpoxe.fairy.core.PluginInstrumentionWrapper.callActivityOnCreate(PluginInstrumentionWrapper.java:279)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                   at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by limpoxe** [comment]
fixed，thx
