### ISSUE TITLE
编译并运行demo,点击plugintest中的打开PluginNormalFragment奔掉问题

### ISSUE THREAD

**Issue by ijoncc** [limpoxe/Android-Plugin-Framework#39]
7.979 13589-13589/com.example.pluginmain:plugin E/Log_StackTrace: 记录错误日志
                                                                               android.view.InflateException: Binary XML file line #76: Binary XML file line #76: Error inflating class com.example.plugintest.view.PluginTestLayout
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                   at com.example.plugintest.fragment.PluginNormalFragment.onCreateView(PluginNormalFragment.java:34)
                                                                                   at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184)
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
                                                                                   at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
                                                                                   at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                                                                                   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
                                                                                   at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                                   at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                                   at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
                                                                                   at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
                                                                                   at com.limpoxe.fairy.core.PluginInstrumentionWrapper.callActivityOnStart(PluginInstrumentionWrapper.java:344)
                                                                                   at android.app.Activity.performStart(Activity.java:6320)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2399)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2496)
                                                                                   at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
                                                                                   at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5457)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                                Caused by: android.view.InflateException: Binary XML file line #76: Error inflating class com.example.plugintest.view.PluginTestLayout
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:649)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
                                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
                                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                   at com.example.plugintest.fragment.PluginNormalFragment.onCreateView(PluginNormalFragment.java:34) 
                                                                                   at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998) 
                                                                                   at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                                   at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607) 
                                                                                   at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181) 
                                                                                   at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238) 
                                                                                   at com.limpoxe.fairy.core.PluginInstrumentionWrapper.callActivityOnStart(PluginInstrumentionWrapper.java:344) 
                                                                                   at android.app.Activity.performStart(Activity.java:6320) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2399) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2496) 
                                                                                   at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362) 
                                                                                   at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5457) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                                                Caused by: java.lang.reflect.InvocationTargetException
                                                                                   at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
                                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
                                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                   at com.example.plugintest.fragment.PluginNormalFragment.onCreateView(PluginNormalFragment.java:34) 
                                                                                   at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998) 
                                                                                   at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                                   at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607) 
                                                                                   at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181) 
                                                                                   at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238) 
                                                                                   at com.limpoxe.fairy.core.PluginInstrumentionWrapper.callActivityOnStart(PluginInstrumentionWrapper.java:344) 
                                                                                   at android.app.Activity.performStart(Activity.java:6320) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2399) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2496) 
                                                                                   at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362) 
                                                                                   at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5457) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                                                Caused by: java.lang.NumberFormatException: Invalid int: "left|right"
                                                                                   at java.lang.Integer.invalidInt(Integer.java:138)
                                                                                   at java.lang.Integer.parse(Integer.java:410)
                                                                                   at java.lang.Integer.parseInt(Integer.java:367)
                                                                                   at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:133)
                                                                                   at android.content.res.TypedArray.getInt(TypedArray.java:357)
                                                                                   at com.example.plugintest.view.PluginTestLayout.<init>(PluginTestLayout.java:28)
                                                                                   at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
                                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
                                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                   at com.example.plugintest.fragment.PluginNormalFragment.onCreateView(PluginNormalFragment.java:34) 
                                                                                   at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092) 
                                                                                   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998) 
                                                                                   at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                                   at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607) 
                                                                                   at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181) 
                                                                                   at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238) 
                                                                                   at com.limpoxe.fairy.core.PluginInstrumentionWrapper.callActivityOnStart(PluginInstrumentionWrapper.java:344) 
                                                                                   at android.app.Activity.performStart(Activity.java:6320) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2399) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2496) 
                                                                                   at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362) 
                                                                                   at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5457) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
02-06 17:38:57.979 13589-13589/com.example.pluginmain:plugin D/AndroidRuntime: Shutting down VM

**Comment by limpoxe** [comment]
编译问题
