### ISSUE TITLE
无法处理xml定义的android:onClick点击事件

### ISSUE THREAD

**Issue by xinghui322** [limpoxe/Android-Plugin-Framework#4]
插件中的布局文件如果在view里定义了android:onClick属性，运行时会crash
错误信息如下：

java.lang.IllegalStateException: Could not find method buttonOnclick(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.widget.Button with id 'btn_comment'
                                                                                                       at android.view.View$DeclaredOnClickListener.resolveMethod(View.java:4767)
                                                                                                       at android.view.View$DeclaredOnClickListener.onClick(View.java:4731)
                                                                                                       at android.view.View.performClick(View.java:5697)
                                                                                                       at android.widget.TextView.performClick(TextView.java:10795)
                                                                                                       at android.view.View$PerformClick.run(View.java:22526)
                                                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                       at android.os.Looper.loop(Looper.java:158)
                                                                                                       at android.app.ActivityThread.main(ActivityThread.java:7197)
                                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1232)
                                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1122)

**Comment by limpoxe** [comment]
Fixed
