### ISSUE TITLE
Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by jason0539** [limpoxe/Android-Plugin-Framework#43]
发现4.x系统有这个问题，以下机型复现
HM 2A                               系统4.4.4
CHM-UL00                       系统4.4.2
vivo X5Max l                     系统4.4.4
三星SCH-I679                   系统4.3
三星Galaxy Tab 3 8.0       系统4.2.2

日志
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.demo.solo/com.demo.solo.stub.PluginStubActivityStandard1}: android.view.InflateException: Binary XML file line #8: Error inflating class com.demo.tuna.GuitarTunaView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2249)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
	at android.app.ActivityThread.access$700(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
	at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5306)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.demo.tuna.GuitarTunaView
	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
	at com.demo.solo.plugin.instrument.TunaActivity.onCreate(TunaActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:5255)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
	at com.limpoxe.fairy.core.PluginInstrumentionWrapper.callActivityOnCreate(PluginInstrumentionWrapper.java:285)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:593)
	... 24 more
Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
	at com.demo.tuna.InstrumentTunaView.<init>(InstrumentTunaView.java:101)
	at com.demo.tuna.GuitarTunaView.<init>(GuitarTunaView.java:19)
	... 27 more
android.view.InflateException: Binary XML file line #8: Error inflating class com.demo.tuna.GuitarTunaView
	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
	at com.demo.solo.plugin.instrument.TunaActivity.onCreate(TunaActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:5255)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
	at com.limpoxe.fairy.core.PluginInstrumentionWrapper.callActivityOnCreate(PluginInstrumentionWrapper.java:285)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
	at android.app.ActivityThread.access$700(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
	at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5306)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:593)
	... 24 more
Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
	at com.demo.tuna.InstrumentTunaView.<init>(InstrumentTunaView.java:101)
	at com.demo.tuna.GuitarTunaView.<init>(GuitarTunaView.java:19)
	... 27 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:593)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
	at com.demo.solo.plugin.instrument.TunaActivity.onCreate(TunaActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:5255)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
	at com.limpoxe.fairy.core.PluginInstrumentionWrapper.callActivityOnCreate(PluginInstrumentionWrapper.java:285)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
	at android.app.ActivityThread.access$700(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
	at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5306)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
	at com.demo.tuna.InstrumentTunaView.<init>(InstrumentTunaView.java:101)
	at com.demo.tuna.GuitarTunaView.<init>(GuitarTunaView.java:19)
	... 27 more
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
	at com.demo.tuna.InstrumentTunaView.<init>(InstrumentTunaView.java:101)
	at com.demo.tuna.GuitarTunaView.<init>(GuitarTunaView.java:19)
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:593)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
	at com.demo.solo.plugin.instrument.TunaActivity.onCreate(TunaActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:5255)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
	at com.limpoxe.fairy.core.PluginInstrumentionWrapper.callActivityOnCreate(PluginInstrumentionWrapper.java:285)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
	at android.app.ActivityThread.access$700(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
	at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:40)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5306)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by jason0539** [comment]
调起的是非独立插件

**Comment by limpoxe** [comment]
请参看Readme注意事项第1条。
