### ISSUE TITLE
PluginAppTrace里create IntentService时有anr问题

### ISSUE THREAD

**Issue by ponyfe** [limpoxe/Android-Plugin-Framework#79]
如下log：

"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x77789e30 self=0xf28ce000
  | sysTid=26093 nice=0 cgrp=default sched=0/0 handle=0xf6483494
  | state=S schedstat=( 612160462 1684489743 1537 ) utm=25 stm=36 core=4 HZ=100
  | stack=0xff797000-0xff799000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x01319495> (a android.os.HandlerThread)
  at android.os.HandlerThread.getLooper(HandlerThread.java:84)
  - locked <0x01319495> (a android.os.HandlerThread)
  at android.app.IntentService.onCreate(IntentService.java:121)
  at android.app.ActivityThread.handleCreateService(ActivityThread.java:3565)
  at android.app.ActivityThread.access$1400(ActivityThread.java:200)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1689)
  at com.limpoxe.fairy.core.PluginAppTrace.handleMessage(PluginAppTrace.java:46)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:201)
  at android.app.ActivityThread.main(ActivityThread.java:6806)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

启动Service的时候，会有比较长时间的耗时，有导致anr的风险，望优化。

**Comment by limpoxe** [comment]
麻烦告知下使用的框架版本号、出现概率和复现步骤 @liangpengfei
