### ISSUE TITLE
独立插件启动会闪退

### ISSUE THREAD

**Issue by 13437543491** [limpoxe/Android-Plugin-Framework#82]
ava.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
        at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(Unknown Source)
        at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source)
        at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
        at com.google.android.gms.common.internal.GoogleApiAvailabilityCache.getClientAvailability(Unknown Source)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zza.connect(Unknown Source)
        at com.google.android.gms.common.api.internal.GoogleApiManager.zzb(Unknown Source)
        at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by limpoxe** [comment]
这个看起来有两个可能，一个是插件apk的manifest确实缺少来gms需要的配置，另外一个是gms的sdk没有正确读到插件apk的manifest的meta数据。第二个可能性比较高。gms可能读到来宿主的manifest而不是插件的。
如果你要集成gms的sdk，需要关注gms的sdk是怎么获取meta的。看下readme结尾的几个文档，有个三方sdk集成相关的问题介绍的解决方法。也适用于独立插件。
