### ISSUE TITLE
studio4.0.1版本下，androidx 在SDK初始化报错

### ISSUE THREAD

**Issue by yihuangxing** [limpoxe/Android-Plugin-Framework#92]
Caused by: java.lang.ClassCastException: androidx.collection.SimpleArrayMap cannot be cast to java.util.Map
        at com.limpoxe.fairy.core.compat.CompatForSupportv7ViewInflater.installPluginCustomViewConstructorCache(CompatForSupportv7ViewInflater.java:27)
        at com.limpoxe.fairy.core.PluginLoader.initLoader(PluginLoader.java:80)
        at com.app.demo.APPAplication.onCreate(APPAplication.java:27)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4606)
        at android.app.ActivityThread.access$1500(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5307) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by yihuangxing** [comment]
自己测试了一把，把androidx注释掉，然后初始化SDK没有问题

**Comment by limpoxe** [comment]
目前AndroidX只支持1.0.0， 其他版本没有适配  另外android gradle plugin版本支持到3.5.3
